"""Create PolicyFlow base schemas after pgvector bootstrap."""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "df20455da62e"  # keep the value generated by Alembic
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create foundational PostgreSQL capabilities."""

    # Business/application state.
    op.execute("CREATE SCHEMA IF NOT EXISTS app")

    # Policy documents, chunks, FTS and vector data.
    op.execute("CREATE SCHEMA IF NOT EXISTS rag")

    # Agent/workflow audit records.
    op.execute("CREATE SCHEMA IF NOT EXISTS audit")


def downgrade() -> None:
    """Remove foundational schemas."""

    op.execute("DROP SCHEMA IF EXISTS audit")
    op.execute("DROP SCHEMA IF EXISTS rag")
    op.execute("DROP SCHEMA IF EXISTS app")
